<?php

namespace HashtagCloudCo\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends EntityRepository
{
    public function getAuthor($uid)
    {

        $query = $this->getEntityManager()->createQuery(

            'select p
 from HashtagCloudCoAdminBundle:Posts p
 where p.user = :id order by p.id asc '
        )->setParameter('id', $uid);

        return $query->getResult();
    }
}
